name: vakeel
description: A personal legal assistant mobile application
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  image_picker: ^1.0.2
  flutter_markdown: ^0.6.17
  loading_animation_widget: ^1.2.0+4
  dio: ^5.3.2
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300